image: Ubuntu1804
stack: node 12
branches: 
  only:
    - master
cache: node_modules
install:
  - yarn
build: off
build_script:
  - yarn build
test_script: 
  - yarn lint && yarn test 
deploy_script: 
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - yarn add push-dir
  - yarn push-dir --dir=dist --branch=gh-pages --force --verbose